[project]
name = "WaveformUncertainty"
authors = [{name = "Ryan Johnson", email = "ryansr71@csu.fullerton.edu"}]
dynamic = ["version", "description"]
dependencies = ['numpy','bilby','scipy','matplotlib']
